version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=3000
    ports:
      - "8081:3000"
    expose:
      - "3000"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=3000
    ports:
      - "8082:3000"
    expose:
      - "3000"
